# Run `travis lint` when changing this file to avoid breaking the build.

cache:
  directories:
  - $HOME/.m2

language: java

jdk: oraclejdk8

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "zipkinci"
  - git config user.email "zipkinci+zipkin-dev@googlegroups.com"
  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

# Override default travis to use the maven wrapper; skip license on travis due to #1512
install: ./mvnw install -DskipTests=true -Dlicense.skip=true -Dmaven.javadoc.skip=true -B -V
script: ./travis/publish.sh

# Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
# See https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^[0-9]/

env:
  global:
    # Ex. travis encrypt BINTRAY_USER=your_github_account
    - secure: "f84wLqsqPo/OmfP/K+FtXn1SNcGGhQa2elPvio/adB6CODdvir5e7mDHAql8zIj5IePzeFvW5RVQMGTDXBDvgVVDCiTdMuY4lRNYyJrMAElrJWJSaoCRW6PpbpRFAZ5zbAbvhgtNsgm1Y8g/0kndnxlOZmxL57W5yDxg3ALf0WhsQUFcE01gVRSRl3/D97NrOAyVSZY4c7WCiVmo9Tp7sIemsGLf/hCQEBbjgtXEJ097WARmEWhNo+6mJKvnSDPhmxK5BU0xRWk+8igfpcY31K4RTc+0hklN3eBOy1yLLzgQEVZXVoAemv3qg2/wOnNxGa0g7r3rn/zB09psY6tVzHfNv67cOuCWmjoeAEV895xSAHGb0XKSuheZbeoXpMKm5JgIeiHySUUGj3wbbt2WPGz+isyYtKgF6xydC60REKVpuOTOsm7YIpKcOehLPyBuhD4gFxBzit0kX5OeCOwr7TQxOTgOsYKGcVJ278X0cVU92dW1gvEWUZzkshVc92SRNIrrTnuAR1uCeZAn3yP2yiJeAJHrFNTtn5Rfsy3YKhg6lCM17CFhZ+AnsXfxBxKE4dYacpyZxQLhYrsfF0v7r4jBE20ughv21rnNSXcTuLJYUPzzJshCGKpXVlvwQS/EweLZ3duIAZ52Sd51O7ZVmDg+KZHy++1LRlho9/QjPoo="
    # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
    - secure: "MHUv+QqNQtvgQdjXqOmLpjyBuwFE/s5j2m9hc27aJ88exJtlmg8SbXg5cnQ81Z7GFm800OeIotEu9DZqYFQobWiIKIV2p0Y3FG58EHTb7yA5VKUq3/bCs8rHDqcub1XnHp3QXE7r2bYJXtWQi2+S2Xx/Lt0Jlb9O4WVd/WNl1NpYFtzPAqwClCqCMTTr9VFCLPO7AnUwhsc95VaBeJdqe3P5A874pEWi7vv7MqEhPLwfgfgtyQ/ulOiQrp1tINAZOmtfWHBkZQYG2wp6ViiLLN5F2MYCf9yVoHuUFeDiOuhAm2poGKvHA6nh3mM9+3dWpRxCm0jZUtU1cefx+a7JAgoH5apfHVSYUhZH/EEgPsuPA2rQ4y4Y7H+Eb9ird6cNgrmMWkNmAJxKPWLtxFphLvjFwDBLWVkEwoQy36PY66S5LKljvXvUOh2muxxcw0MQYdhwTFwV2DxSsNXv4UbJKui+oUOcPyi37JDO+6SNdCBY8Rgir7RG5gOp8wDMLWWOnIfWzqu/HNAKTLbe+8+wsx2TuwUnuM0xzevpfHTAigbtKzU3gmYujyBoalRajC/H2gMZByFktSN4i6aQBJt9JzmhSHVRmN5/MZEwqqQvwZ5k5znIcbfWmL+nf4sOkqECg8NLy/K7Y35n5nHxRMSJmOEzdv76QTDBlfOAbYPwDDI="
    # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
    - secure: "q/TAuVSj+SPF6QHkkd1QI6B8GqaDojq9AxmRZ9DUfMYBOszzc9zZZDvh0qpMbqRMdYTGexnK42Z654etgvHaWc+C7UhCSCndrWJE3GMF6C+CwdlVvxcZ5BTKrTOhoioww039jgAwvVV3Jv5tbqKLYpMcG1KSNVyrkJL0GO/Q7AbWLIMjd4YRKx2TPvZ1EUFGvQZtsz5qz0eLq9CuFfzIO9nOxwxavDBYBWP4CLgKCFNUImGc/LiZU54laCMtoUkl41bOmTeuJK2hTkcXtqNmptmAZiEItUBmqYzA8ZTw/wv0XysVYmUfDozsaaW/W6M/otDlj8HaOE5wJqjizhUP/Fy/A1wKioINnm+IrlMxUUIMG+/WbId4LsmVDpeE+KuA1lZ4Gp69fi86qIEpb+qInTMRFmDe65IpmJzKuBBgdQhPo/CAo5WHFd4t3NTIK7NTW0o4OuT/KNybJxeBCj9Uf8u8yR+7R3lMmISyGYcolZmgIbqbHAHn0Wjf+5XxtIzQca555RXlcPHMnAqUoDdzz2W2sp4lp3W4gggJqabchhGEZw7ZdOmCeeax68QgBJDMk6O97vF8i0H/ePoh8MFCVUtlCxxfXQGAUjxjmFalbpmh62cxUysm6yxJNt/9qIs/3AWejpuh+jjezjPdvzoUDFfsRLxUf3wmUHHZXVUsTVs="
    # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
    - secure: "PUWmzrTDOacmR4Ai64PgB+FSWgTpULBlqlrzTyuPRI5HsF+7EjMOfB18qheTbA2GdV87dUcR46yr9ixD3ltY2Ni5hkPaGKyqGfLHNy0RhAvhQcdD7HXhtjriL1pHZdKU/SDsqkuCVZWTXNVXUB/RVz5u9f2cRW68+h4CAC02yirnNRt4/xjdB37Tldki4X+5LMvJWcW+LA9o1G3QkLk8RfTbzT6YcxCSAV8XqdH6CTMSTuzbn+m8uR2t0oX+rUsY3pLw10p9hUrnfEGTTKubRx8jzBonHUsFnnmJ6IntK/pTPxK0H1sMb1kCsfaZ/tR4Zgz2zAQWe96q7oB/zU8Fd0PnFK4NLBZ96GkYynnWV9yhjzDeBbgXvTVH40IyTbSGcwPjnTe1290WgBJlukFTTWmpUuAVVLPgGX0q6r6xQZv91fxH6Vzwl/KWs9CxELuP6A60rRzKsxLa2ktkRznnMcokJpvhUwhzPvmrf0F7r8DQ0cT6DhOC6lp7IfQXlAXCEwbtarp4baCnKJL2nG2BYlMFyEieVKJNSa4Sdb9yBpDckolL+J3QZGBOVcjeLyMAASo3SS3FpVsjmBUpHJDJP05XWhl8MSSNd6YLAFsCCrppKQ0ch1Dhdubs+m0ymA29KkF8qS+PfHAB3tk5Bflmz4LQqhqpoQt0OKupJtjod1E="
    # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
    - secure: "iIZwYdtHnZS0cWt9K9Z9udOftagEwbx2ct8dKANQyDsTqjF2oAAHIyyJtoeJsxTVe2OXYKLSGYJiWMNaagSRW/30uE46d6TrZ0VLrEIGl8tO2ZqfSanNDwqUx52WvBgZr5IirOnrSLdiGKAju4Rs6K1/NNAo+zRBrgv5OL/S72KORDYRWD7vca3uh/BSNDgMY8i3TJzV0OcFZnFbjQo5lEx+9iEr9tJKaiVnlY+GRaz5P6X7rmtxm7x7a3EpeBWla0jHR0lhJGeWhQwkCS95iFTJYK220n9HyL0Km5HF0zU9imDOuVdJN9t+VjsZ+rC287XoiJcZjazd/hWkaWV9ZAOtZBZD8zCE1ojnLmEgOprt9EwSLs7UrMwiP4GMQkkSZxJMAVBfJwqXI+FrixDybpj41pymUedLQ9pA9LQKb4C9ag7N/nSifcEMbk9hucMbpJTbGpG/GmkvuzgG3aHSNyoaEsUlFtsfrignaZQtspNzhTW/HQ5gN4Yc/MOy7fAMT1rCOMTh3G8Hs9zSsln8MkUIZM+Vqtft6cls0RvwPsnBeiFd6xyhdlksY2HGABF97zq6gc5Twv2Q1q/Z7spK2TrO5AS88EWXqGQz4zafWBox5uEPWEPS353RZcJ6pO4NLCrEnhwqMRh/QQi5R7XxpIe4MLepXXeT/QcY+7LprCY="
